const express = require("express");
const createSheet = require("../../controllers/sheet/create");
const deleteSheet = require("../../controllers/sheet/delete");
const ChangeSheetStatus = require("../../controllers/sheet/completeSheet");
const getAllSheetsByBranchId = require("../../controllers/sheet/get/getAllSheetsByBranchId");
const getDeliveryGuySalaryDetails = require("../../controllers/sheet/get/getDeliveryGuySalaryDetails");
const getDeliveryGuyWorkSummary = require("../../controllers/sheet/get/getDeliveryGuyWorkSummary");
const getFifteenDayWorkSummary = require("../../controllers/sheet/get/getFifteenDayWorkSummary");
const getStaffSalaryDetails = require("../../controllers/sheet/get/getStaffSalaryDetails");
const getLatestFourSheets = require("../../controllers/sheet/getLatestFourSheets");
const getLatestFourStaffSheets = require("../../controllers/sheet/getLatestFourStaffSheets");
const getTotal = require("../../controllers/sheet/get/getTotal");
const router = express.Router();

router.get("/salary/staffSalary/:id", getStaffSalaryDetails);
router.get("/salary/deliveryGuySalary/:id", getDeliveryGuySalaryDetails);
router.get("/daySummary/:tableId", getFifteenDayWorkSummary);
router.get("/deliveryGuySummary/:tableId", getDeliveryGuyWorkSummary);
router.get("/deliveryGuySalary/:branchId", getLatestFourSheets);
router.get("/staffSalary/:branchId", getLatestFourStaffSheets);
router.get("/total", getTotal);
router.get("/", getAllSheetsByBranchId);
router.post("/", createSheet);
router.post("/changeStatus", ChangeSheetStatus);
router.delete("/:id", deleteSheet);
module.exports = router;
